volumes:
  open_animal_rescue_local_postgres_data: {}
  open_animal_rescue_local_postgres_data_backups: {}


services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: open_animal_rescue_local_django
    container_name: open_animal_rescue_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: open_animal_rescue_production_postgres
    container_name: open_animal_rescue_local_postgres
    volumes:
      - open_animal_rescue_local_postgres_data:/var/lib/postgresql/data
      - open_animal_rescue_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
