# Generated by Django 5.0.9 on 2024-09-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('feedback_type', models.CharField(choices=[('SUGGESTION', 'Suggestion'), ('COMPLIMENT', 'Compliment'), ('COMPLAINT', 'Complaint')], default='SUGGESTION', max_length=80)),
                ('feedback', models.TextField(blank=True, default='')),
            ],
        ),
    ]
