# Generated by Django 5.0.9 on 2024-09-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('class_name', models.CharField(choices=[('MAMMAL', 'Mammal'), ('REPTILE', 'Reptile'), ('BIRD', 'Bird'), ('AMPHIBIAN', 'Amphibian'), ('INSECT', 'Insect')], default='REPTILE', max_length=20)),
                ('description', models.TextField()),
                ('diet', models.CharField(choices=[('VEGGIE', 'Veggie'), ('CARNIVORE', 'Carnivore'), ('MIXED', 'Mixed'), ('INSECT', 'Insect'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=80)),
                ('is_ohio_native', models.BooleanField(default=False)),
            ],
        ),
    ]
