# Generated by Django 5.0.9 on 2024-10-02 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_animal_medicalrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='findings',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='problem_list',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
