# Generated by Django 5.0.9 on 2024-10-02 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_medicalrecord_findings_medicalrecord_problem_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='vet_cleared_date',
            field=models.DateTimeField(null=True),
        ),
    ]
