# Generated by Django 5.0.9 on 2024-10-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_animal_vet_cleared_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('ON_HOLD', 'On Hold'), ('AVAILABLE', 'Available'), ('QUARANTINED', 'Quarantined'), ('FOSTERED', 'Fostered'), ('MEDICAL_HOLD', 'Medical Hold'), ('ADOPTED', 'Adopted'), ('DECEASED', 'Deceased'), ('AMBASSADOR', 'Ambassador')], default='AVAILABLE', max_length=80),
        ),
    ]
