# Generated by Django 5.0.9 on 2024-09-19 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=80)),
                ('last_name', models.CharField(default='', max_length=80)),
                ('email', models.EmailField(default='donotemail@example.com', max_length=254)),
                ('phone_number', models.CharField(default='555-5555', max_length=20)),
                ('type', models.CharField(choices=[('ADOPTER', 'Adopter'), ('DONOR', 'Donor'), ('VOLUNTEER', 'Volunteer'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=80)),
                ('address', models.CharField(default='', max_length=250)),
                ('zip_code', models.IntegerField(default=44121)),
                ('notes', models.TextField(blank=True, default='')),
                ('roles', models.ManyToManyField(to='people.role')),
            ],
        ),
    ]
