# Generated by Django 5.0.9 on 2024-10-05 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='type',
        ),
    ]
